#!/bin/sh

#cd /web/planet.creativecommons.org/software
cd /var/www/cc/planet/software

# Update the easy planets
python planet.py ../config/people/config
python planet.py ../config/jurisdictions/config

# Now, do the lol maneuver of creating the root config file:
cat ../config/jurisdictions/config ../config/people/config ../config/root/config.root > ../config/root/autogenerated-super-massive-config-DO-NOT-EDIT-THIS

# And generate the evil front page
python planet.py ../config/root/autogenerated-super-massive-config-DO-NOT-EDIT-THIS
