#!/bin/sh

# root will get the an email from cron based on the output, but if this
# email should go to other people, then add them to the RCPT_TO variable,
# space separated. (nkinkade 2008-02-08)
RCPT_TO="michelle@creativecommons.org" # mail errors to these people

ERR_FILE=/tmp/planet_errors # a file where errors are output

cd /var/www/planet.creativecommons.org/software

# Update the easy planets
python planet.py ../config/community/config
python planet.py ../config/jurisdictions/config

# Now, do the lol maneuver of creating the root config file:
cat ../config/jurisdictions/config ../config/community/config ../config/root/config.root > ../config/root/autogenerated-super-massive-config-DO-NOT-EDIT-THIS

# And generate the evil front page
python planet.py ../config/root/autogenerated-super-massive-config-DO-NOT-EDIT-THIS &> $ERR_FILE

# if there were any errors, then mail them to someone
if [ -s $ERR_FILE ]; then
    cat $ERR_FILE | mail -s "CC Planet Venus Errors" $RCPT_TO
fi;

# remove the error file
rm $ERR_FILE
